# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fri',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='mon',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='thu',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='tue',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='wed',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
